name:                KeyboardGenerator
version:             0.1.0.0
github:              "kevroletin/thumb-friendly-keyboard"
license:             BSD3
author:              "Vasiliy Kevroletin"
maintainer:          "kevroletin@gmail.com"
copyright:           "2018 Vasiliy K."

extra-source-files:
- README.md
- ChangeLog.md

extra-doc-files:
- doc/img/*.png

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            not-intended-for-hackage-category

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/kevroletin/thumb-friendly-keyboard#readme>

dependencies:
- base >= 4.7 && < 5
- GlomeVec
- mtl

library:
  source-dirs: src

executables:
  main-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - KeyboardGenerator

tests:
  3d-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - KeyboardGenerator
